### ISSUE TITLE
issues with long protein chains

### ISSUE THREAD

**Issue by josef0731** [Fraternalilab/PDBencode#1] opened 2021-03-05 17:28 UTC
There is an issue with long protein chains - if residue number is 4 digits long it seems the reading of file (handled by bio3d) has a problem? 

I discovered this using pdb 7c2l. This is the error message:

```
Error in kabsch_C(4, pdb.xyz[((3 * x) - 2):((3 * x) + 9)], sadata_o@fragment_coordinates[[y]]) : 
  NA/NaN/Inf in foreign function call (arg 2)
Calls: sapply ... lapply -> FUN -> sapply -> lapply -> FUN -> kabsch_C

```

I tested using 7c2l again, but this time including only chain A up to position 999. This error does not appear in that case.

**Comment by jkleinj** [comment] 2021-03-05 19:48
The problem is that we have (A-N) protein chains and (O-l) chains containing only pyranose NAG (O-l).
https://www.rcsb.org/ligand/NAG
Because the R script loops over all chains and needs at least 4 sequential CA atoms to assign an alphabet letter,
the encoder fails on those pyranose chains.
I'll add a filter to loop only over chains that contain 4+ CA atoms.

If you remove the O-l chains from the PDB file, all the proteins chains will be encoded.

**Comment by jkleinj** [comment] 2021-03-06 18:31
Fixed now in release v.0.3 with the following condition in *pdbencode.R*:
```{r}
if (length(ca.inds$atom) < 4) {
  message("  Chain not encoded: <4 CA atoms")
  return()
}
```
Chains with less than 4 CA atoms will be skipped.
They will not be listed in the *sasta* output file.

**Closed as completed by jkleinj** 2021-03-06 18:31 UTC
